"""added category tables

Revision ID: 922359b65cf2
Revises: fe89bbd903dc
Create Date: 2024-01-14 09:06:04.648561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '922359b65cf2'
down_revision: Union[str, None] = 'fe89bbd903dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('trader_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_category'), 'category', ['category'], unique=False)
    op.create_index(op.f('ix_category_colour'), 'category', ['colour'], unique=True)
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.drop_index('ix_traders_id', table_name='traders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_traders_id', 'traders', ['id'], unique=False)
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_index(op.f('ix_category_colour'), table_name='category')
    op.drop_index(op.f('ix_category_category'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
